name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy

      - name: Code formatting with Black
        run: |
          black --check --diff . || echo "Black formatting issues found"
        continue-on-error: true

      - name: Import sorting with isort
        run: |
          isort --check-only --diff . || echo "Import sorting issues found"
        continue-on-error: true

      - name: Linting with flake8
        run: |
          flake8 . --count --exit-zero --max-complexity=15 --max-line-length=150 --ignore=E203,W503,E501 --statistics
        continue-on-error: true

      - name: Type checking with mypy
        run: |
          mypy networksecurity/ --ignore-missing-imports || echo "Type checking completed with warnings"
        continue-on-error: true