name: Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM

jobs:
  dependency-check:
    name: Dependency Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools pip-audit

      - name: Check for outdated packages
        run: |
          pip list --outdated --format=json > outdated-packages.json || true

      - name: Validate requirements.txt
        run: |
          pip-compile --dry-run requirements.txt || echo "Requirements validation completed"

      - name: Check for security vulnerabilities
        run: |
          pip-audit --format=json --output=vulnerability-report.json || true

      - name: Upload dependency reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dependency-reports
          path: |
            outdated-packages.json
            vulnerability-report.json