name: Performance Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  performance-test:
    name: Performance Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install locust memory-profiler

      - name: Memory profiling
        run: |
          python -m memory_profiler app.py > memory-profile.txt || echo "Memory profiling completed"

      - name: Load testing setup
        run: |
          echo "Setting up load testing environment"
          python simple_server.py &
          sleep 5

      - name: Basic load test
        run: |
          curl -f http://localhost:8000/test || echo "Load test completed"

      - name: Upload performance reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-reports
          path: |
            memory-profile.txt